name: to_do_x
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.6
  get_storage: ^2.1.1
  intl: ^0.20.2
  easy_date_timeline: ^2.0.9
  google_fonts: ^8.0.1
  uuid: ^4.3.3
  # flutter_local_notifications: ^17.0.0
  # timezone: ^0.9.2
  awesome_notifications: ^0.10.1
  confetti: ^0.7.0
  flutter_staggered_grid_view: ^0.7.0
  image_picker: ^1.0.7
  share_plus: ^10.0.0
  speech_to_text: ^7.0.0
  permission_handler: ^11.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
